FROM golang:1.20 AS build

WORKDIR /usr/src/test-enclave

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/test-enclave

FROM alpine:latest AS release

WORKDIR /

COPY --from=build /usr/local/bin/test-enclave .

ENTRYPOINT ["/test-enclave", "server", "5005"]
