FROM golang:1.20

WORKDIR /usr/src/test-enclave

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -v -o /usr/local/bin/test-enclave ./...

CMD ["test-enclave", "client"]
