// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: grpc/instance.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VirtualDeviceWallet_GetAddress_FullMethodName = "/test_enclave.VirtualDeviceWallet/GetAddress"
)

// VirtualDeviceWalletClient is the client API for VirtualDeviceWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualDeviceWalletClient interface {
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
}

type virtualDeviceWalletClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualDeviceWalletClient(cc grpc.ClientConnInterface) VirtualDeviceWalletClient {
	return &virtualDeviceWalletClient{cc}
}

func (c *virtualDeviceWalletClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	out := new(GetAddressResponse)
	err := c.cc.Invoke(ctx, VirtualDeviceWallet_GetAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualDeviceWalletServer is the server API for VirtualDeviceWallet service.
// All implementations must embed UnimplementedVirtualDeviceWalletServer
// for forward compatibility
type VirtualDeviceWalletServer interface {
	GetAddress(context.Context, *GetAddressRequest) (*GetAddressResponse, error)
	mustEmbedUnimplementedVirtualDeviceWalletServer()
}

// UnimplementedVirtualDeviceWalletServer must be embedded to have forward compatible implementations.
type UnimplementedVirtualDeviceWalletServer struct {
}

func (UnimplementedVirtualDeviceWalletServer) GetAddress(context.Context, *GetAddressRequest) (*GetAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedVirtualDeviceWalletServer) mustEmbedUnimplementedVirtualDeviceWalletServer() {}

// UnsafeVirtualDeviceWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualDeviceWalletServer will
// result in compilation errors.
type UnsafeVirtualDeviceWalletServer interface {
	mustEmbedUnimplementedVirtualDeviceWalletServer()
}

func RegisterVirtualDeviceWalletServer(s grpc.ServiceRegistrar, srv VirtualDeviceWalletServer) {
	s.RegisterService(&VirtualDeviceWallet_ServiceDesc, srv)
}

func _VirtualDeviceWallet_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualDeviceWalletServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualDeviceWallet_GetAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualDeviceWalletServer).GetAddress(ctx, req.(*GetAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualDeviceWallet_ServiceDesc is the grpc.ServiceDesc for VirtualDeviceWallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualDeviceWallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test_enclave.VirtualDeviceWallet",
	HandlerType: (*VirtualDeviceWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _VirtualDeviceWallet_GetAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/instance.proto",
}
