name: build-app-image
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpushdev
    runs-on: [self-hosted,enclave]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./resources/enclaveimage/Dockerfile
          push: false
          platforms: linux/amd64
          tags: dimozone/synthetic-wallet-enclave:${{ steps.slug.outputs.sha7 }}

