name: build-enclave-tools

on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_kms_tools:
    # The type of runner that the job will run on
    name: build kms tools
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout enclave sdk
        uses: actions/checkout@v4
        with:
          repository: 'aws/aws-nitro-enclaves-sdk-c'
          path: 'aws-nitro-enclaves-sdk-c'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Build and push builder
        uses: docker/build-push-action@v3
        with:
          file: ./aws-nitro-enclaves-sdk-c/containers/Dockerfile.al2
          push: true
          context: ./aws-nitro-enclaves-sdk-c
          target: builder
          platforms: linux/amd64
          tags: dimozone/aws-nitro-enclaves-sdk-c:latest
      - name: Build and push kmstool-enclave-cli
        uses: docker/build-push-action@v3
        with:
          file: ./aws-nitro-enclaves-sdk-c/containers/Dockerfile.al2
          push: true
          context: ./aws-nitro-enclaves-sdk-c
          target: kmstool-enclave-cli
          platforms: linux/amd64
          tags: dimozone/kmstool-enclave-cli:latest   
  build_nitro_cli:
    # The type of runner that the job will run on
    name: build nitro-cli image
    runs-on: self-hosted
    steps:
      
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push enclave builder
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./resources/enclavebuilderimage/Dockerfile
          push: true
          platforms: linux/amd64
          tags: dimozone/nitro-enclave-builder:latest
  

