name: build-enclave-image-dev
on:
  push:
    branches:
      - main
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app:
    # The type of runner that the job will run on
    name: build-app
    runs-on: [self-hosted]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Build and push enclave app
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./resources/appimage/Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: dimozone/synthetic-wallet-enclave-app:${{ steps.slug.outputs.sha7 }}, dimozone/synthetic-wallet-enclave-app:latest

  build-enclave:
    name: build-enclave
    runs-on: [self-hosted,enclave]
    needs: build-app
    container:
      image: dimozone/nitro-enclave-builder:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      volumes:
        - ${{ github.workspace }}/build/output:/build/output
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Build enclave
        run: nitro-cli build-enclave --docker-uri dimozone/synthetic-wallet-enclave-app:${{ steps.slug.outputs.sha7 }} --output-file /build/output/synthetic-wallet-enclave.eif
      - uses: actions/upload-artifact@v3
        with:
          name: synthetic-wallet-enclave
          path: ${{ github.workspace }}/build/output/synthetic-wallet-enclave.eif

  build-final-image:
    # The type of runner that the job will run on
    name: build-final-image
    runs-on: [self-hosted]
    needs: build-enclave
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
 
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      
      - uses: actions/download-artifact@v3
        with:
          name: synthetic-wallet-enclave
          path: ${{ github.workspace }}/resources/docker/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: dimozone/synthetic-wallet-enclave:${{ steps.slug.outputs.sha7 }}, dimozone/synthetic-wallet-enclave:latest