name: Manual trigger

on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpushdev
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout enclave sdk
        uses: actions/checkout@v4
        with:
          repository: 'aws/aws-nitro-enclaves-sdk-c'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./containers/Dockerfile.al2
          push: true
          target: builder
          platforms: linux/amd64
          tags: dimozone/aws-nitro-enclaves-sdk-c:latest

